### ISSUE TITLE
Show charts with cumulative doses delivered vs. administered per vaccine type

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/covid-19-vaccinations-germany#34]
Requested by @evilpie, here: https://twitter.com/evilpies/status/1398310284809412608

**Comment by evilpie** [comment]
Very cool, thank you! As an additional bonus the sum of all weeks would also be interesting.

From my understanding the vaccine deliveries on https://impfdashboard.de/ don't actually include the current week. So in theory you can get more than 100%. But I haven't checked if you are actually using that information.

**Comment by mathiasbynens** [comment]
> From my understanding the vaccine deliveries on https://impfdashboard.de/ don't actually include the current week. So in theory you can get more than 100%. But I haven't checked if you are actually using that information. 

Correct. We automatically display a warning when doses administered exceeds doses delivered: https://github.com/mathiasbynens/covid-19-vaccinations-germany/blob/b7643861ebf2a9bf4405f93a6d07aeccf4355b0e/templates/chart.template#L54-L56

**Comment by mathiasbynens** [comment]
I've added an initial version of this now, albeit per-day rather than per-week.

I've noticed there's a drop on 2021-04-26 in the per-vaccine charts for both [Pfizer/BioNTech](https://mathiasbynens.github.io/covid-19-vaccinations-germany/#per-vaccine-biontech) and [Oxford/AstraZeneca](https://mathiasbynens.github.io/covid-19-vaccinations-germany/#per-vaccine-astrazeneca). TODO: investigate whether this matches the source spreadsheets.

**Comment by evilpie** [comment]
I actually think this version is better than just per week. One graph per vaccine makes this very readable. Great work.

**Comment by mathiasbynens** [comment]
Thanks :)

I'll keep the issue open until we figure out what's going on with the 2021-04-26 drop. I won't get to this today, so in case anyone wants to help, here's what to do: compare the Pfizer/BioNTech- and Oxford/AstraZeneca-specific numbers in the following two source sheets:

- https://github.com/evilpie/Impfquotenmonitoring/blob/master/Impfquotenmonitoring-2021-04-24T07:59:54.xlsx
- https://github.com/evilpie/Impfquotenmonitoring/blob/master/Impfquotenmonitoring-2021-04-26T06:51:22.xlsx

…and report back.

**Comment by evilpie** [comment]
I think the relevant files for 2021-04-26 are
- https://github.com/evilpie/Impfquotenmonitoring/blob/master/Impfquotenmonitoring-2021-04-27T07:13:08.xlsx
- https://github.com/evilpie/Impfquotenmonitoring/blob/master/Impfquotenmonitoring-2021-04-27T07:44:50.xlsx

At least for Pfizer/Biontech there was some change here from 19,603,335 in the 07:13 file to 18,830,416 in the 7:44 file. The former is probably closer to reality. But neither match the 16,309,838 on the chart. And it's actually higher than what is reported for 4-27 on the chart again.

**Comment by evilpie** [comment]
I also noticed that 7:44 added a column for Jansen.

**Comment by mathiasbynens** [comment]
In the “Impfstoff_bis_einschl_26.04.21” sheet of https://github.com/evilpie/Impfquotenmonitoring/blob/master/Impfquotenmonitoring-2021-04-27T07:44:50.xlsx, the result of `D22+I22` is 16,309,838. I suppose `O22` and `T22` should be added too.
