### ISSUE TITLE
FYI: global regional vaccination data

### ISSUE THREAD

**Issue by lucasrodes** [mathiasbynens/covid-19-vaccinations-germany#7]
Hi! 
This is just an "FYI" message. First of all, thanks for your amazing resource. Inspired by OWID's project, I started a global collection of regional vaccination data and I am using yours (see [sociepy/covid19-vaccination-subnational](https://github.com/sociepy/covid19-vaccination-subnational)) 😄 !

So far I have referenced it in a reference table in the README file, but please let me know if you'd like it to be referenced differently.

Have a great day and feel free to close this issue!

**Comment by mathiasbynens** [comment]
That's amazing! I was hoping people would use this data for their own projects. I love the CSV structure you're outputting, very clean. Thanks for letting me know about your project! I'll add a link to it from this project's README 👍

**Comment by lucasrodes** [comment]
Thanks for your words (and your work, again) @mathiasbynens, appreciate it! =)
